### ISSUE TITLE
Issue with settings

### ISSUE THREAD

**Issue by KittenPixel** [ernesto-glz/discord-clone#3]
When you try to change username the input boxes don't work

**Comment by KittenPixel** [comment]
```index.bc09a3c6.js:2108 Uncaught TypeError: Cannot read properties of undefined (reading 'username')
    at index.bc09a3c6.js:2108:92490
    at Array.map (<anonymous>)
    at Kte (index.bc09a3c6.js:2108:92472)
    at Qte (index.bc09a3c6.js:2108:92572)
    at qv (index.bc09a3c6.js:30:19536)
    at kS (index.bc09a3c6.js:32:3173)
    at DL (index.bc09a3c6.js:32:45175)
    at NL (index.bc09a3c6.js:32:40042)
    at JG (index.bc09a3c6.js:32:39970)
    at Fu (index.bc09a3c6.js:32:39824)```

 Found the error maybe yall can get it fixed to bad it doesn't have the actual file names.

**Comment by KittenPixel** [comment]
Might of been a startup bug
